FROM python:3.8-slim-buster 

WORKDIR /app

RUN pip install python-dotenv

RUN python3 -m pip install -U discord.py

ADD democracyBot.py /app

ADD gifs /app/gifs/

ADD .env /app

CMD ["python3", "./democracyBot.py"]
