FROM python:3.8-slim-buster 

WORKDIR /app

RUN pip install --upgrade pip

RUN pip install python-dotenv

RUN python3 -m pip install -U discord.py

RUN useradd -u 8877 botMan

USER botMan

ADD democracyBot.py /app

ADD gifs /app/gifs/

ADD .env /app

CMD ["python3", "./democracyBot.py"]
